version: '2'
services:
  builder:
    image: robbrazier/php:builder
    build:
      context: ./builder
  php55:
    image: robbrazier/php:5.6
    build:
      context: ./5.5
  php56:
    image: robbrazier/php:5.6
    build:
      context: ./5.6
  php70:
    image: robbrazier/php:7.0
    build:
      context: ./7.0
  php71:
    image: robbrazier/php:7.1
    build:
      context: ./7.1
  php72:
    image: robbrazier/php:7.2
    build:
      context: ./7.2
  phplatest:
    image: robbrazier/php:latest
    build:
      context: ./latest
