#!/bin/bash
set -e

PUID=${PUID:-root}
PGID=${PGID:-root}

chown -R $PUID:$PGID $COMPOSER_HOME

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

gosu $PUID:$PGID "$@"