#!/bin/bash
set -e

PUID=${PUID:-www-data}
PGID=${PGID:-www-data}

chown -R $PUID:$PGID $COMPOSER_HOME

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

gosu $PUID:$PGID "$@"